### ISSUE TITLE
Suggestion: Offer more data

### ISSUE THREAD

**Issue by dehsgr** [alphaess-developer/alphacloud_open_api#1]
It would be nice if you would offer more data or make open these calls too:
- SticsByDay
- SystemStatistic

Maybe an option could be to define some limits for being able to open those API calls.

These data are used e.g. for generating those graphs:
![C1BDE22C-8117-47D8-BA11-46883ED66F52](https://user-images.githubusercontent.com/4125820/201917336-5c886348-f9b9-4985-9082-236b5b492aba.jpeg)
![C4B2ECE5-0202-4B93-B605-3534CE6F981F](https://user-images.githubusercontent.com/4125820/201917344-e8e025d2-36b8-4324-8605-7f9c11e467c6.jpeg)

**Comment by ElevenFan** [comment]
@dehsgr After our negotiation, these two interfaces can be added, but the time will be a bit long, first add 4 interfaces, and the public API cancels the Token。

**Comment by dehsgr** [comment]
@ElevenFan thanks for negotiating and the resulting decision.

What do you mean with „public API cancels the token“. Will there be a timeline where we’re not able to fetch that data or can we use current and open API side-by-side until this is implemented?

**Comment by ElevenFan** [comment]
Now I will not modify the key of the current system

**Comment by IAmKonni** [comment]
Additionally i would like to control the charging/discharging power by e.g. setting power limits. Sometimes I don't like discharging with max 3 kW.

**Comment by crowdstrike-steve** [comment]
from my side the exiting functionality i use is 
**GetLastPowerDataBySN**
-> to get the real time energy flow

**GetCustomUseESSSetting & setSystemSettings**
to first get the setting payload and then modify to set the charge %.
Once set, i set the battery to gird charging at time X. I then use GetLastPowerDataBySN to monitor the data flow, once it drops below 1kw for 1 minute i stop the grid changing and use the battery

Other than that, i use the login api call.

I have noticed that the payload for the Expiry time on the token has changed format far too often (US format, EU format, then i saw some Chinese characters) so if forced me to ignore the expiry time and re-login on error.

 I've noticed its not possible to determine when charging the battery if its being charged from the grid or the sun.
 (maybe there is a flag and i didn't see it)
 
 
 hope this helps

**Comment by ElevenFan** [comment]
@dehsgr  After the user registers an account, a Develop ID and a Developkey will be created，The Develop ID, Develop Key and timestamp are encrypted with SHA512 as a signature, and each request needs to be added，The preliminary plan is like this, so that there is no need to login  interface and refresh  Token interface。When our website is finished, we will know how to develop it。

**Comment by ElevenFan** [comment]
@IAmKonni At first, we must developed  the basic Api。
