### ISSUE TITLE
POST commands results in 6026 error

### ISSUE THREAD

**Issue by bnc-rainman** [alphaess-developer/alphacloud_open_api#11]
Already discussed offtopic in an other issue here again as own issue

**Request**
![image](https://user-images.githubusercontent.com/5917059/220877113-853abcc4-4f54-43df-a9d0-238a6d74bbe3.png)

**Response**
`{
    "code": 6026,
    "data": null,
    "expMsg": null,
    "msg": "org.springframework.security.web.firewall.StrictHttpFirewall$StrictFirewalledRequest$1@565592fe"
}`

**Comment by ElevenFan** [comment]
I test it ,it can return success.  @bnc-rainman 
![image](https://user-images.githubusercontent.com/117050711/220900130-1472f263-f49b-4d19-b642-b9ee67854c0e.png)

**Comment by bnc-rainman** [comment]
Hello @ElevenFan,

 it works on my side now too. Thank you very much.

Please update the documentation from "Request Parameters" to some kind of "Attributes in a JSON formated body payload" or insert an other explanation in the API documentation.

**Comment by ElevenFan** [comment]
Problem solved, issus closed。
