### ISSUE TITLE
Registration with long passwords broken?

### ISSUE THREAD

**Issue by chrisgeli** [alphaess-developer/alphacloud_open_api#13]
I recently tried to register on the open.alphaess.com website, using a password generated by a password manager (I believe it was 24 characters long).

The registration process *appeared* to be successful, but when I tried to log in with the same credentials, it failed with the message "Passwords do not match".

I tried the Forget Password feature, but after changing it (to another long password), it failed with the same message when trying to log in.

Registering with a shorter password (12 characters) worked fine.

I suggest the following improvements to the open.alphaess.com web portal:

 * supporting longer passwords to help security
 * when trying to register with a password that cannot be supported for any reason, give that feedback to the user before advancing in the registration process to avoid registering with a password that cannot be used during login.

**Comment by ElevenFan** [comment]
@chrisgeli I think this is a good suggestion。You find a bug。Thanks。I will schedule this update。

**Comment by ElevenFan** [comment]
The bug has been resolved。
