### ISSUE TITLE
Are there any bugs in the current Api?

### ISSUE THREAD

**Issue by ElevenFan** [alphaess-developer/alphacloud_open_api#14]
Do you still encounter bugs during the closed beta? If there is no problem, I plan to officially release it on the official website at the end of March. Please put forward some other good suggestions in time in #10 , whether it can be realized and opened up, our product department will consider it.Thanks。

**Comment by RizzoRat** [comment]
getOneDateEnergyBySn returns undocumented redundant data: (with different parameter name capitalization, for example eoutput vs. eOutput): - also the (documented) parameter eGirdCharge has a typo and should be named eGridCharge
```
(json decoded, from debugger:)
		code	200	int
		msg	Success	string
-		data	{table}	{table (15) }
		eInput	6.9	float
		eCharge	8	float
		theDate	2023-03-01	string
		eoutput	3.58	float
		edischarge	7.3	float
		echargingPile	0	float
		egirdCharge	0.3	float
		einput	6.9	float
		epv	18.8	float
		sysSn	NONEOFYOURBUSINESS	string
		eOutput	3.58	float
		echarge	8	float
		eDischarge	7.3	float
		eChargingPile	0	float
		eGirdCharge	0.3	float
		expMsg	null	null

```

**Comment by matt-oneill** [comment]
Get ESS List showing wrong battery capacity (cobat) and Battery Capacity remaining (surplusCobat).
Should this be based on the total installed capacity, rather than a single battery? Or can it provide the capacity & remaining for each battery?
`
{
            "sysSn": "xxxx",
            "popv": 0.00,
            "minv": "Storion-SMILE-B3",
            "poinv": 3.00,
            "cobat": 2.87,
            "mbat": "M4856-P",
            "surplusCobat": 2.5830,
            "usCapacity": 90.00,
            "emsStatus": "Normal"
        }
`

**Comment by RizzoRat** [comment]
I'm a bit baffled - First, getEssList is undocumented in developer portal for private users. GetCustomMenuESSList  does not show up anywhere, what is it? Plus, the current python demo script seems outdated regarding getChargeInfo and getDisChargeInfo (using getInChargeConfigInfo and getOutChargeConfigInfo, which return a 404. Did not test update methods yet)
While this is no bug in the API itself, so to say, it's... odd and you should not release in this state of documentation & demo code 

Or am I missing something?
Can I maybe have a second account with integrator state for checking? (indeed we're a software dev company, I just made a private account because we have no invitation code)

**Comment by matt-oneill** [comment]
> I'm a bit baffled - getCustomMenuEssList does not show up anywhere, what is it? Plus, the current python demo script seems outdated regarding getChargeInfo and getDisChargeInfo (using getInChargeConfigInfo and getOutChargeConfigInfo, which return a 404. Did not test update methods yet) While this is no bug in the API itself, so to say, it's... odd and you should not release in this state of documentation & demo code
> 

@RizzoRat getCustomMenuEssList is an endpoint in the current (non open) alpha api which appears to return the same data as getEssList in the open api documentation.

**Comment by RizzoRat** [comment]
Opps. Should have read ElevenFans initial post more closely... :P

**Comment by dehsgr** [comment]
@ElevenFan getEssList endpoint seems to return wrong data:
- popv returns same as poinv (10 kW, should be: 12.75 kW)
- emsStatus returns "Fault" (Monitoring cloud shows "Normal")

**Comment by dehsgr** [comment]
getOneDayPowerBySn seems to return data with random order. Not sure if this is your intention. Furthermore I'm unsure how to get total consumption from that endpoint for the specific day. All calculations don't reflect consumption from monitoring portal.

**Comment by RizzoRat** [comment]
@dehsgr Looks like the portal shows eInput+epv-eGirdCharge-eOutput as consumption (so it ignores pv charging and discharging, which will be approx. correct when the battery gets a balanced cycle from PV that day and the day has completely passed), while real world load energy probably should be calculated eInput+eDischarge+epv-eCharge-eOutput-eGirdCharge, which should also work during the current day and be more precise overall)

**Comment by dehsgr** [comment]
Thank you very much @RizzoRat for directing me in the right direction! Shouldn't (-)eChargingPile being included in your second formula too for catching up all parameters?

**Comment by RizzoRat** [comment]
possibly, I don't have access to a system providing that, so its always 0 for me (and hence for now I don't understand how it works.... :-D )

**Comment by ElevenFan** [comment]
> getOneDayPowerBySn seems to return data with random order. Not sure if this is your intention.
> 
> Furthermore I'm unsure how to get total consumption from endpoint getOneDateEnergyBySn for the specific day. All calculations don't reflect consumption from monitoring portal.

@dehsgr This data is 5-minute level data， EMS will upload this data and the evaluation rate is 5 minutes，getLastPowerData is 10S data

**Comment by ElevenFan** [comment]
@RizzoRat I can't modify this formula, it's set by our company。

**Comment by dehsgr** [comment]
@ElevenFan okay, but what‘s about the order of each item returned by getOneDayPowerBySn? It seems to be random instead of chronological order…

**Comment by dehsgr** [comment]
I see, but normally server should should return in correct order. 🤷🏼‍♂️

**Comment by Gaspode69** [comment]
In my case the request returns the data ordered by uploadTime descending.

**Comment by dehsgr** [comment]
@Gaspode69 strange – today it's ordered correctly at my site too!

**Comment by Gaspode69** [comment]
@dehsgr 
Lessons learned: Do not rely on the order of data delivered by the open Alpha-ESS API ;-)
Good that we know it now right from the beginning.

**Comment by dehsgr** [comment]
@Gaspode69 I've to recall my last statement. Ordering seems to be okay for past dates. For the current date it is random order. Can you confirm this?

**Comment by Gaspode69** [comment]
@dehsgr 
2023-03-07: random (today)
2023-03-06: random (yestarday)
2023-03-05: descending
2023-03-04: descending
2023-03-03: descending

But as I understood @ElevenFan it is generally not a good ideo to rely on any order.

**Comment by ElevenFan** [comment]
@dehsgr @Gaspode69 We will modify the program for this sort。

**Comment by dehsgr** [comment]
@ElevenFan looks great! Thank you for fixing this!

**Comment by matt-oneill** [comment]
@ElevenFan thanks for sorting the ordering, are you going to sort any of the incorrect values before releasing to the official website?

**Comment by ElevenFan** [comment]
> @ElevenFan thanks for sorting the ordering, are you going to sort any of the incorrect values before releasing to the official website?

Which interface has not been sorted ?getOneDayPowerBySn i update yesterday。

**Comment by matt-oneill** [comment]
> > @ElevenFan thanks for sorting the ordering, are you going to sort any of the incorrect values before releasing to the official website?
> 
> Which interface has not been sorted ?getOneDayPowerBySn i update yesterday。

@ElevenFan 3 incorrect values in getEssList. my correct current values provided alongside below. also mentioned above by @dehsgr 

- popv returns same as poinv (10 kW, should be: 12.75 kW)
- emsStatus returns "Fault" (Monitoring cloud shows "Normal")

```
"sysSn": "ALXXXXXX",
"popv": 0.00,                => 4.5
"minv": "Storion-SMILE-B3",
"poinv": 3.00,
"cobat": 2.87,               => 14.34
"mbat": "M4856-P",
"surplusCobat": 2.5830,      => 13.8
"usCapacity": 90.00,
"emsStatus": "Normal"
```

**Comment by ElevenFan** [comment]
@matt-oneill We will update this bug on Monday，Thank you for your feedback on this question。

**Comment by ElevenFan** [comment]
@matt-oneill    Yestaday I update it ,you can try to test it!

**Comment by matt-oneill** [comment]
> @matt-oneill Yestaday I update it ,you can try to test it!

@ElevenFan sorry have been away this week. Almost there, surplusCoBat still doesn't match the original API or the website

**Comment by matt-oneill** [comment]
@ElevenFan how is development progressing? 
surplusCoBat still isn't correct. 
Also, I've just noticed something else.
On the website its possible to enter discharge cutoff SOC of 4% `Discharging Cutoff SOC [%]:(4.0--100.0)`
But on updateDisChargeConfigInfo api an error is returned
`{
    "code": 0,
    "msg": "batUseCap must be in 5~100!",
    "expMsg": null,
    "data": null
}`

**Comment by ElevenFan** [comment]
@matt-oneill update it，you can try to test it。Api can be set range is fixed。

**Comment by Gaspode69** [comment]
In my case updateDisChargeConfigInfo still allows for discharging cutoff SOC only values equal or greater to 5.

**Comment by ElevenFan** [comment]
Sorry, OpenApi can only be set to this range at present。

**Comment by Gaspode69** [comment]
Hi @ElevenFan, one small (documentation) bug:

I sent accidentally a boolean value for attribute ctrDis in a call of getDisChargeConfigInfo (should be int).
I received error code 6026, which is not documented.

**Comment by ElevenFan** [comment]
Now I update it。

**Comment by ElevenFan** [comment]
close
