### ISSUE TITLE
Question: Will all users of the API have to register at open.aplhaess?

### ISSUE THREAD

**Issue by Gaspode69** [alphaess-developer/alphacloud_open_api#15]
@ElevenFan 
As stated before, many of us are planning to use the API in open source projects. What are the plans for accessing the API after the beta test is over? Will each user of this open source software has to create an account at open.alpahess and to register his equipment?

**Comment by ElevenFan** [comment]
This test is just to invite some people to participate in the test. If there is no problem with the test, I will publish it on the official website. The official release will not release the account of the Beta test. Secondly, some suggestions will be adopted.

**Comment by ElevenFan** [comment]
close issues
