### ISSUE TITLE
Strange behavior when setting batUseCap using updateDisChargeConfigInfo

### ISSUE THREAD

**Issue by Gaspode69** [alphaess-developer/alphacloud_open_api#16]
@ElevenFan 
My test:
the value of batUseCap was at 40% for a couple of days until yesterday, 03/10/2023 9:12 a.m. At this time I set batUseCap to 41%:
   ```
 const body = {
        'batUseCap': 41,
        'ctrDis': 0,
        'timeDise1': '00:00',
        'timeDise2': '00:00',
        'timeDisf1': '00:00',
        'timeDisf2': '00:00',
        'sysSn': sysSn
    };
    const res = await postRequest('updateDisChargeConfigInfo', body, {});
```
Everything looked fine, also in the Alpha-ESS app 41% was displayed. I then changed batUseCap to 10% at 03/10/2023 8:00 p.m. and again everything looked fine.
```
const body = {
     'batUseCap': 10,
     'ctrDis': 0,
     'timeDise1': '00:00',
     'timeDise2': '00:00',
     'timeDisf1': '00:00',
     'timeDisf2': '00:00',
     'sysSn': sysSn
 };
```
 const res = await postRequest('updateDisChargeConfigInfo', body, {});
However, this morning 03/11/2012 00:00, batUseCap changed from 10% to 40% and this was not me. This was the second time that I observed that batUseCap was set to an old value at midnight automatically. Can you please verify. This does not happen when I change batUseCap using the Alpha ESS portal or app.

**Comment by ElevenFan** [comment]
@Gaspode69 Please send mail to “service@alpha-ess.com”，mail title is “OpenApi question”，Write down your SN in the email。

**Comment by Gaspode69** [comment]
Mail is sent.

**Comment by Gaspode69** [comment]
Just a short summary after a short discussion with @ElevenFan on Slack:
It is not strange, it is simply not working yet. ;-)
Setting batUseCap via open API sets the value in the portal, but the change is not sent to the Alpha ESS device (in my case Simle 5).
@ElevenFan is working on it.

**Comment by ElevenFan** [comment]
@Gaspode69  this bug i update it, you can try to test it

**Comment by Gaspode69** [comment]
@ElevenFan 
Works. Thank you.

**Comment by ElevenFan** [comment]
Close issues
