### ISSUE TITLE
Problems with API since 2023/04/23 0:56

### ISSUE THREAD

**Issue by joffi-wonder** [alphaess-developer/alphacloud_open_api#19]
Hi,
i using the API since 2023/04/14 with httpmod in FHEM and it works like a charme!
Since tomorrow i get an error:
, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://openapi.alphaess.com/api/getEssList')
This is from the demo python script.
And from FHEM:
2023.04.26 08:45:08 3: PV_API: no parsed JSON structure available
LG
Frithjof

**Comment by Gaspode69** [comment]
Same here, I get error code 502 since today, 2023/04/26. Yesterday it was working.

**Comment by ElevenFan** [comment]
Now It is ok,server disk full.I receive a lot of requests and write logs frequently，The disk is full, and the log is now closed.
@joffi-wonder @Gaspode69

**Comment by Gaspode69** [comment]
Thanks. Works again.

**Comment by joffi-wonder** [comment]
Thanks a lot!
