### ISSUE TITLE
Best wishes for your devs!

### ISSUE THREAD

**Issue by dehsgr** [alphaess-developer/alphacloud_open_api#2]
I hope that your developers will have a mild course of disease and wish a speedy recovery. Come well into the new year!

**Comment by ElevenFan** [comment]
Thank you, the developers are already in place, the Api has been developed, and we are doing testing and language translation

**Comment by dehsgr** [comment]
That sounds really good! ♥️

Stay healthy – I‘ll close this „issue“ now.
