### ISSUE TITLE
API do not reachable tody

### ISSUE THREAD

**Issue by joffi-wonder** [alphaess-developer/alphacloud_open_api#20]
Hi all,
since 2023/04/29 12:59 the https://openapi.alphaess.com/api/getSumDataForCustomer
return error code 6025
since 23:39:45
https://openapi.alphaess.com/api/getLastPowerData? 
not reachable.
I use it to power up my heaing rod with FHEM.

**Comment by jmfremion** [comment]
agree - request timed out

**Comment by petekelly** [comment]
Same for me

**Comment by paulbusse** [comment]
And me .. but I could connect on may 3 16:49 CET

**Comment by ElevenFan** [comment]
Close
