### ISSUE TITLE
getOneDateEnergyBySn always MSG Error 6053

### ISSUE THREAD

**Issue by joffi-wonder** [alphaess-developer/alphacloud_open_api#22]
Hi,
getlastPowerData works again.
getOneDateEnergyBySN (poll every 300s) i alway get Error 6053.
c:\Temp\alphacloud_open_api-main>py alpha_api_demo.py
https://openapi.alphaess.com/api/getEssList
{'appId': 'alpha3e3fa429c957fe42', 'timeStamp': '1683837272', 'sign': '14d18aa3acf39bdc51ecc3dec424ec093b253583265080dfe7d61f2d54420a34018afe4f6f8d1eee3390946138fc9f5f67b0d9179c37a1fe045576c08cbad414'}
{}
{'code': 6053, 'msg': None, 'expMsg': None, 'data': None}
Get ess list error: 6053 None
None
https://openapi.alphaess.com/api/getLastPowerData
{'appId': 'alpha3e3fa429c957fe42', 'timeStamp': '1683837272', 'sign': '14d18aa3acf39bdc51ecc3dec424ec093b253583265080dfe7d61f2d54420a34018afe4f6f8d1eee3390946138fc9f5f67b0d9179c37a1fe045576c08cbad414'}
{'sysSn': 'ALB002022083131'}
{'code': 200, 'msg': 'Success', 'expMsg': None, 'data': {'ppv': 0.0, 'soc': 62.8, 'pev': 0, 'pgrid': 60.0, 'pbat': 810.0, 'pload': 870.0}}
{'ppv': 0.0, 'soc': 62.8, 'pev': 0, 'pgrid': 60.0, 'pbat': 810.0, 'pload': 870.0}
https://openapi.alphaess.com/api/getOneDateEnergyBySn
{'appId': 'alpha3e3fa429c957fe42', 'timeStamp': '1683837273', 'sign': '95995518f1a7ec82e7998266e9282a5fdaa190a5627df6a755e9c453380af082005dfb949d4ff6bd5979130df401d66d316749bc1bc3fb21ca8d67402798e02f'}
{'sysSn': 'ALB002022083131', 'queryDate': '2023-05-05'}
{'code': 6053, 'msg': None, 'expMsg': None, 'data': None}
Get one date energy by SN error: 6053 None

The same with FHEM and HTTPMOD.

best regards

**Comment by ElevenFan** [comment]
@joffi-wonder Api interface has been limited,

**Comment by Gaspode69** [comment]
@ElevenFan 
Yes, but he wrote he gets Error 6053 for getOneDateEnergyBySN even if he waits 300s between requests.
In my tests requesting getOneDateEnergyBySN works fine if I wait 300s between the requests.

**Comment by ElevenFan** [comment]
So I need look at his program。

**Comment by joffi-wonder** [comment]
Hi,
if use the demo python file
with some modification

# get one day of energy eata for the specific ESS
    # return a list of dicts of energy data (probably, untested)
    async def get_sum_data_for_customer(self, sn, date):
        path = "getSumDataForCustomer"
        params = {"sysSn": sn, "queryDate": date}
        r = await self.__get_request(path, params)
        if r is not None:
            if r['code'] == 200:
                return r['data']
            else:
                logger.error(f"Get sum data for customer: {r['code']} {r['msg']}")
    ...
async def example_code() -> None:
    alpha = AlphaESSAPI()

    # adminitrative related
    bound_systems_info = await alpha.get_ess_list()
    print(bound_systems_info)
    sys_sn = 'ALB002022083131'  # as an example, can acquire from bound_system_info

    
    # data related
    last_power_data = await alpha.get_last_power_data(sys_sn)
    print(last_power_data)
    #one_date_power = await alpha.get_one_date_power_by_sn(sys_sn, "2023-05-12")
    #print(one_date_power)
    #one_date_energy = await alpha.get_one_date_energy_by_sn(sys_sn, "2023-05-12")
    
    get_system_summary = await alpha.get_sum_data_for_customer(sys_sn, "2023-05-12")
    print(get_system_summary)
