### ISSUE TITLE
getSumDataForCustomer returns code 6026

### ISSUE THREAD

**Issue by DirtyHairy** [alphaess-developer/alphacloud_open_api#23]
Calling `getSumDataForCustomer` I always end up with code 6026 (or, unsuprisingly, with 6053 if I hit the rate limit):

```
{"code":6026,"msg":null,"expMsg":null,"data":null}
```

Curiously, the same request already worked for me when experimenting last week --- could it be that there currently is an issue with the API?

For reference, this is a shell script that performs the request that I am using via curl:

```
#!/bin/bash

DATE="2023-05-13"
SERIAL="xxx"
SECRET="xxx"
APPID="xxx"
TIMESTAMP=`date '+%s'`
HASH=`echo -n "${APPID}${SECRET}${TIMESTAMP}" | sha512sum | awk '{print $1}'`

echo curl -H "appId: $APPID" -H "timeStamp: $TIMESTAMP" -H "sign: $HASH" -v \
    "https:/openapi.alphaess.com/api/getSumDataForCustomer?sysSn=${SERIAL}&queryDate=${DATE}"

curl -H "appId: $APPID" -H "timeStamp: $TIMESTAMP" -H "sign: $HASH" -v \
    "https:/openapi.alphaess.com/api/getSumDataForCustomer?sysSn=${SERIAL}&queryDate=${DATE}"
```

I have redacted my personal data from the script for obvious reasons, but I can provide you with the S/N if you'd like to look it up in your logs.

**Comment by Gaspode69** [comment]
Same here.

**Comment by paulbusse** [comment]
Same here. It stopped working on May 12.
Is there an overview of these error codes?

**Comment by paulbusse** [comment]
@Gaspode69:  My apologies, I should have been more clear. I did find that link before. However that link does not explain the codes we are discussing here in github: e.g. 6053 and 6026. Those numbers suggest that there are plenty more error codes besides the 10 in the link you provided.

**Comment by Gaspode69** [comment]
The link has a second page. ;-)

<html><body>


Code | Description
-- | --
6011 | timestamp is empty
6012 | AppId is empty
6026 | internal error
6046 | Verification code error
6053 | The request was too fast, please try again later


</body>
</html>

**Comment by ElevenFan** [comment]
Let me check it

**Comment by ElevenFan** [comment]
@DirtyHairy Do you use slack? I want to know your SN, I will test it

**Comment by Gaspode69** [comment]
@ElevenFan 
I have the same issue, I'll send you my S/N on slack

**Comment by Gaspode69** [comment]
Works again on my side.

**Comment by DirtyHairy** [comment]
Hm, still the same error for me.

**Comment by DirtyHairy** [comment]
@ElevenFan If you send me a Slack invite link, I can give you my S/N

**Comment by ElevenFan** [comment]
@DirtyHairy Please send email to “service@alpha-ess.com”，email title is “Join alphaess Slack”，Thanks

**Comment by paulbusse** [comment]
I had it working yesterday from 11:30 through 14:40 CET. Since then it keeps returning the 6026.

**Comment by Gaspode69** [comment]
Also for me, it stopped working again.

**Comment by DirtyHairy** [comment]
> @DirtyHairy Please send email to “[service@alpha-ess.com](mailto:service@alpha-ess.com)”，email title is “Join alphaess Slack”，Thanks

Done.

**Comment by paulbusse** [comment]
Working stable since May 19 08:52:26 (UTC+2)
