### ISSUE TITLE
Q: Rate Limits for querying the API

### ISSUE THREAD

**Issue by th-s-op** [alphaess-developer/alphacloud_open_api#27]
Are there any rate limits to keep track of, especially for the realtime data, or for querying historical data?
Is there a "good practice" you'd like to see from API users, i.e. the minimum time between two realtime requests?

Thank you, great API!

**Comment by CharlesGillanders** [comment]
I believe Alpha have asked that requests don't happen any more frequently than every 30 seconds.

**Comment by Gaspode69** [comment]
Limits are described here:
https://github.com/alphaess-developer/alphacloud_open_api/issues/21#issuecomment-1537096354

**Comment by Gaspode69** [comment]
@ElevenFan 
Will missing features be added to OpenApi? I will still the following data:

* Power per string
* Power per Phase

And will the rate limits stay so restrictive?

**Comment by Gaspode69** [comment]
Hi @ElevenFan 
are there also rate limits for the charger functions:

getEvChargerConfigList
getEvChargerCurrentsBySn
getEvChargerStatusBySn
remoteControlEvCharger

How often is it allowed to call these?

**Comment by ElevenFan** [comment]
The limit is a 1S limit based on each AppID + interface name.
