### ISSUE TITLE
Support for a Home Assistant integration

### ISSUE THREAD

**Issue by ingeniumdesign** [alphaess-developer/alphacloud_open_api#3]
Hi and thanks for the new API.  
Home Assistant is the bigges Smarthome-Software in world.  
Can you add a integration?  

https://www.home-assistant.io/integrations/

here is a custom version:  
https://github.com/CharlesGillanders/homeassistant-alphaESS

**Comment by ckarrie** [comment]
+1 i.e. a local polling integration should reduce your API traffic

**Comment by ElevenFan** [comment]
The polling control is once in 10S。

**Comment by Spookster** [comment]
It would be great if there was local polling to increase the speed and reliability of the data. It would also reduce the 80000000 hits per second you are worried about....
