### ISSUE TITLE
GetLastPowerDataBySN returns Error: 6053 though it is not called faster than every 10 seconds

### ISSUE THREAD

**Issue by Gaspode69** [alphaess-developer/alphacloud_open_api#30]
Hi,
according to [here](https://github.com/alphaess-developer/alphacloud_open_api/issues/21#issuecomment-1537096354) it is allowed to call GetLastPowerDataBySN every 10 seconds. From time to time error 6053 (The request was too fast, please try again later) is raised, anyhow.

**Comment by ElevenFan** [comment]
We are unified interface for the same server

**Comment by Gaspode69** [comment]
Sorry, what do you mean with that?

**Comment by Gaspode69** [comment]
Wait a minute. Are you telling me that I cannot use the Open API from two end points at the same time?
This would be a very big limitation.

**Comment by ElevenFan** [comment]
The normal limit is a 1S limit based on each AppID + interface name.But GetLastPowerDataBySN Today we lifted his restrictions and read his data from Redis. I tried it without restrictions to see the effect. @Gaspode69
