### ISSUE TITLE
Extend Documentation for curl cli

### ISSUE THREAD

**Issue by kellerassel007** [alphaess-developer/alphacloud_open_api#32]
This snippet works for me using curl cli for the API:

REQUEST_TIMESTAMP=$(date +%s) # has to be current timestamp, requested pv data date is in curl GET param queryDate
SIGN=$(echo -n "${ALPHA_ESS_APP_ID}${ALPHA_ESS_APP_SECRET}${REQUEST_TIMESTAMP}" | sha512sum | cut -d ' ' -f1)

curl --fail-with-body -H "appId: ${ALPHA_ESS_APP_ID}" -H "timeStamp: ${REQUEST_TIMESTAMP}" -H "sign: ${SIGN}" -X GET "https://openapi.alphaess.com/api/getOneDayPowerBySn?queryDate=${DATE_STRING}&sysSn=${SN_NUMBER}"

**Comment by ElevenFan** [comment]
What？

**Comment by kellerassel007** [comment]
Just add the given code snippet as example, how to send a request to API using curl

**Comment by ElevenFan** [comment]
Which development language did you use?

**Comment by kellerassel007** [comment]
> Which development language did you use?

It's bash (linux) script using curl which is a standard http request cli tool. Pretty nice for CI/CD jobs or if you don't want to install any programming language frameworks, libs...
