### ISSUE TITLE
getVerificationCode: error msg for code 6002 is incorrect

### ISSUE THREAD

**Issue by jbanyer** [alphaess-developer/alphacloud_open_api#34]
When calling `/api/getVerificationCode` with an invalid sysSn (eg "asdfasdf"), the API returns a code 6002 however the error msg is incorrect:

```
{"code":6002,"msg":"The SN is not bound to the user","expMsg":null,"data":null}
```

**Comment by ElevenFan** [comment]
This prompt indicates that this SN does not have a registered end user. In our view this system does not exist。

**Comment by jbanyer** [comment]
Yes, so for code 6002, would a better error message be "SN does not exist"?
