### ISSUE TITLE
About API

### ISSUE THREAD

**Issue by ElevenFan** [alphaess-developer/alphacloud_open_api#36]
Please do not use the website’s API. The current website’s API will be further strengthened. If we update it every time, you will have to update with us every time.
Although website anti-crawling data has not been added now, we may add these functions in a week or a month.
But we will not modify the functions in openapi casually. Although there are imperfections, I need your feedback.
API Limitations Currently, many customers initiate 50,000 API requests in 1 second, which puts too much pressure on our server.
There are some interface restrictions, such as charging and discharging. Frequent settings will cause the FLASH flash frequency to be too high and burn the FLASH.
Sorry, my English is not very good here。

**Comment by jbanyer** [comment]
What kind of client would send 50,000 API requests in 1 second? Surely that is not necessary.

**Comment by ElevenFan** [comment]
There was an unusual period of time when I first went online.

**Comment by jbanyer** [comment]
Perhaps some clients had a bug when they connected to your API and went into a loop, sending many requests.

Or somebody attacked the API with a Denial-of-Service attack.

Whatever it was, hopefully we can all together adjust the API rate limits to protect the API whilst also meeting the requirements of clients where they are reasonable and fair.
