### ISSUE TITLE
Request for individual real time power measurements

### ISSUE THREAD

**Issue by CharlesGillanders** [alphaess-developer/alphacloud_open_api#37]
The OpenAPI only provides a combined figure for Grid and PV real time power readings. The web API which we must stop using has individual measurements for each phase for the Grid as well as each separate string for PV generation.

This is a request to extend the OpenAPI to provide the individual real time power readings as well as the combined figures.

**Comment by Gaspode69** [comment]
I totally agree. In my opinion this is the main reason why many users keep using the inofficial web API.
Please add this to the OpenAPI.

**Comment by UdoG62** [comment]
It wouldn't be nice to see the additional options being lost. I need all the strings for east and west orientation
please keep the closed alive

**Comment by bennohaf** [comment]
That is also my opinion. In order to analyze the performance of the two roof sides separately, I need the string to be displayed separately. Please add these objects to the openAPI. Thanks!

**Comment by ElevenFan** [comment]
Can you provide the required fields?  @Gaspode69 @CharlesGillanders

**Comment by Gaspode69** [comment]
@ElevenFan 

I currently use:
GetLastPowerDataBySN
- pmeter_l1
- pmeter_l2
- pmeter_l3
- ppv1
- ppv2
- ppv3
- ppv4
- pmeter_dc
- preal_l1
- preal_l2
- preal_l3
- ev1_power
- ev2_power
- ev3_power
- ev4_power

**Comment by bennohaf** [comment]
My requirements are the same as @gaspode

**Comment by ElevenFan** [comment]
Is this the only one?

**Comment by bennohaf** [comment]
these are the ones I'm currently missing in openAPI

**Comment by CharlesGillanders** [comment]
> Is this the only one?

That's all that is needed.

**Comment by ElevenFan** [comment]
@Gaspode69 @CharlesGillanders @UdoG62 @bennohaf I have received your requests and will arrange development in the near future. Please wait patiently.

**Comment by ElevenFan** [comment]
{
    "code": 200,
    "msg": "Success",
    "expMsg": null,
    "data": {
        "ppv": 1200,
        "ppvDetail": {
            "ppv1": 1200,
            "ppv2": 0,
            "ppv3": 0,
            "ppv4": 0,
            "pmeterDc": 0
        },
        "soc": 50,
        "pev": 1,
        "pevDetail": {
            "ev1Power": 1,
            "ev2Power": 0,
            "ev3Power": 0,
            "ev4Power": 0
        },
        "prealL1": 500,
        "prealL2": 0,
        "prealL3": 0,
        "pload": 4580,
        "pbat": 2500,
        "pgrid": 880,
        "pgridDetail": {
            "pmeterL1": 880,
            "pmeterL2": 0,
            "pmeterL3": 0
        }
    }
}

@Gaspode69 @CharlesGillanders Will update the program today、

**Comment by iaincoulter** [comment]
Guessing PPV1 and PPV2 are strings one and two, what about 3 and 4?  If running my smile5 in hybrid mode is PPV3 for the external inverter ?
Or do I need to subtract ppv1+ppv2  from total ppv value  to get the generation from external inverter?

**Comment by Gaspode69** [comment]
@iaincoulter 
Should be pmeter_dc

**Comment by Gaspode69** [comment]
@ElevenFan 
Just a quick feedback: The additional attributes are working as expected. Thank you! 👍
