### ISSUE TITLE
getVerificationCode endpoint does not send emails

### ISSUE THREAD

**Issue by jbanyer** [alphaess-developer/alphacloud_open_api#38]
The `/api/getVerificationCode` returns success (code = 200) however no email is received by the end user.

Requesting a verification code via open.alphaess.com does work - the email is received by the end user.

Our bind workflow is performed by the end-user, and the end-user must be ready to check their email, so it's important that the API can send verification code emails.

**Comment by jbanyer** [comment]
@ElevenFan any update on this problem?

I have about 80 users trying to connect, and each one is taking many emails back-and-forth because I have to send the verification code and they have to use it within 30 minutes. It's not really possible unless we can send verification codes using the API. Thanks!

**Comment by ElevenFan** [comment]
OK， We will update

**Comment by jbanyer** [comment]
> OK， We will update

Thanks Eleven. Please let us know when this is fixed, so I can tell our end-users to connect.

**Comment by jbanyer** [comment]
FYI some customers are reporting that the verification code emails are now working when requested by the API. So I think this issue is fixed?
