### ISSUE TITLE
suggestion: extend the expiry of verification codes

### ISSUE THREAD

**Issue by jbanyer** [alphaess-developer/alphacloud_open_api#39]
Currently the verification codes expire after 30 minutes.

We have already experienced several end-users who don't find their verification code in time, and it expires. This leads to increased support work, confusion and unhappy end-users.

Can the expiration be extended? Perhaps up to 24 hours? Any increase would be helpful.

Thanks.

**Comment by ElevenFan** [comment]
@jbanyer You can try to test it
