### ISSUE TITLE
Error adding system

### ISSUE THREAD

**Issue by matt-oneill** [alphaess-developer/alphacloud_open_api#4]
Hi @ElevenFan, thanks to the team for the hard work so far.
I have registered at open.alphaess.com, but not able to add my system

I have entered the SN, and a random string for check code (values removed in screen shot)
On clicking 'Get verification code' the error is displayed.
![image](https://user-images.githubusercontent.com/60574293/219494790-97a9531e-481d-4169-86f4-aff3bd8d7167.png)

**Comment by ElevenFan** [comment]
It is still in the beta stage, if you have any questions, please ask。Thanks。

**Comment by matt-oneill** [comment]
Thanks @ElevenFan have added it successfully now. I know its in beta, but I wanted to give it a try!
