### ISSUE TITLE
Login no longer works

### ISSUE THREAD

**Issue by ajhurst** [alphaess-developer/alphacloud_open_api#40]
My username/password ceased to authenticate me at 0630 4 Nov 2023 (UTC), and I have no idea what might have caused this.  How can I reset the password please?

**Comment by ElevenFan** [comment]
User forget password

**Comment by ajhurst** [comment]
OK, maybe we are talking at cross purposes.  I am trying to use the  alphaESS API interface, written by Charles Gillanders (see https://pypi.org/project/alphaess/) which has a straightforward username/password to authenticate.  This is the combination that is failing.  Is this related to alphaess-developer, or are we on different wavelengths?

**Comment by CharlesGillanders** [comment]
> OK, maybe we are talking at cross purposes.  I am trying to use the  alphaESS API interface, written by Charles Gillanders (see https://pypi.org/project/alphaess/) which has a straightforward username/password to authenticate.  This is the combination that is failing.  Is this related to alphaess-developer, or are we on different wavelengths?

My library (currently) uses the alphaESS web api which Alpha has asked us to stop using and to switch to use this open API instead.

I'm intending to move my home assistant integration to use this API and will stop developing the original library.

The web api was never supported by AlphaESS, this api is supported so it makes sense to transition even if there's an extra step required for setup.

**Comment by ajhurst** [comment]
Thank you for that information, most helpful.  I have just tried to create an account with alphaess-developer, and most of it seems straightforward.  But it asks for a "CheckCode", which I could not find on my system.  How do I find out what my CheckCode is?  TIA !

**Comment by ElevenFan** [comment]
![image](https://github.com/alphaess-developer/alphacloud_open_api/assets/117050711/950e72dd-0f66-45b6-b46c-0ad76453367d)

**Comment by ajhurst** [comment]
Thank you!   Login now succesful.  Now to transition as Charles suggests ...

**Comment by ajhurst** [comment]
Transition successful!  Thank you all for your help!
