### ISSUE TITLE
getVerificationCode fails for some systems

### ISSUE THREAD

**Issue by jbanyer** [alphaess-developer/alphacloud_open_api#41]
Hi Eleven,

As you know, the `getVerificationCode` endpoint is failing with an error for some systems. You mentioned this occurs with older systems.

I've supplied some examples in Slack.

The verification code can be generate by me using open.alphaess.com using the codes above, but because the verification codes expire after 30 minutes this workflow is not possible, as the end-user will not be ready, and it requires manual work by me which is not scalable.

Are you able to fix this so the `getVerificationCode` works for these older systems?

**Comment by matt-oneill** [comment]
@jbanyer should you be posting your customers serial numbers and check codes?

**Comment by jbanyer** [comment]
> @jbanyer should you be posting your customers serial numbers and check codes?

No, probably not. I've removed the details now, and put them in Slack.

**Comment by jbanyer** [comment]
@ElevenFan this issue is not fixed - we still receive errors for all the sysSn I sent you in Slack

**Comment by ElevenFan** [comment]
This problem will not be solved. In addition, OpenAPI found that there was commercial activity and immediately disabled account processing.
