### ISSUE TITLE
Is there an API for retrieving grid status?

### ISSUE THREAD

**Issue by CraigN** [alphaess-developer/alphacloud_open_api#42]
I'd like to be able to monitor my grid and detect when the grid is unstable (low voltage, frequency variation) or offline (power failure).

Ideally I'd like to know the grid voltage (V) and frequency (Hz).

**Comment by ElevenFan** [comment]
This OpenAPI is not supported and requires a more professional level API.

**Comment by KortgatGH** [comment]
@CraigN I fully agree that we require a way to monitor grid status. In the past on my NodeRed Alpha ESS node I had an entity called "ups_model" under the raw data. Although strangely named it corresponded 100% with the grid status on my Smile-5. Since the Node-Red node moved over to the "official" API it disappeared there too.

**Comment by ElevenFan** [comment]
This is another mode and has nothing to do with this.

**Comment by ElevenFan** [comment]
This is wrong. The ups_mode field has been deprecated.

**Comment by CraigN** [comment]
Surely there is a way of surfacing this data?

**Comment by KortgatGH** [comment]
It is such a fundamental parameter in a system like this, and essential for home automation. I suspect there may be other problems that triggered the decision to remove it. I had a Smile-5 and the UPS mode didn't quite behave as expected. For unrelated reasons my Smile-5 was replaced under warranty with a later model Smile-5 and then the UPS mode worked perfectly. So maybe someone is expecting too many questions from older Smile-5 owners. One would think that a firmware update on the older Smile-5's would solve it though. There is still an "off-grid" flag on the web interface. Could we perhaps in the meantime scrub it off there?
