### ISSUE TITLE
Loop Battery Management

### ISSUE THREAD

**Issue by matt-oneill** [alphaess-developer/alphacloud_open_api#43]
Hi @ElevenFan ive received an email from loop today to manage my battery charging and discharging during power saving sessions. 
to sign up for this they need serial number and check code so I guess they are using this api. 
https://blog.loop.homes/loop-alphaess

My question is if loop are claiming to be able to discharge to the grid automatically why aren’t we able to set this within the Alpha web portal, or by using this api?
All we are able to set is discharge time control, not discharging to grid.

**Comment by ElevenFan** [comment]
Only electric power companies can perform this discharge to the power grid. For this discharge API, you need to apply for the professional version of the API, and you must be an electric power company.

**Comment by matt-oneill** [comment]
What is the application process for the other api?

**Comment by ElevenFan** [comment]
You can contact our local sales。
