### ISSUE TITLE
Sensors not reseting at local midnight - Instead at UTC, and not returning to Zero

### ISSUE THREAD

**Issue by gregpetersau** [alphaess-developer/alphacloud_open_api#44]
When using the API my daily cumulative sensors like Charge, Discharge, solar production etc are not reset to zero at midnight - instead they are resetting at UTC-0 Midnight, which for me is 11am.

Secondly, they are not resetting to Zero but some random amount. As a result the numbers are climbing higher and higher.

Clock and time zone is set correctly in website and data shows correctly in the app. Problem is api only

How to fix? 

![Screenshot_20231120-073450](https://github.com/alphaess-developer/alphacloud_open_api/assets/97826055/b0db0f25-4857-43da-bf55-e17dc4a0b6f6)
![Screenshot_20231120-073331](https://github.com/alphaess-developer/alphacloud_open_api/assets/97826055/05e81320-fe9e-4569-a54a-7d0d24ab60a6)

**Comment by Poshy163** [comment]
The "random" amount seems to be it just catching up with the current value its meant to be outputting, localizing the API based off of a selected inverter timezone, or one set via the API dashboard would be ideal.

**Comment by ElevenFan** [comment]
What？

**Comment by Poshy163** [comment]
Apologies, after digging into the source code of the implementation, it appears to be a implementation error, rather than an API error. 

Can marked this as closed
