### ISSUE TITLE
API calls are case sensitive even though getESSList always returns upper case SN

### ISSUE THREAD

**Issue by CharlesGillanders** [alphaess-developer/alphacloud_open_api#48]
If a SN has been bound to an AppID using lower case letters then the API calls for that SN must be made using lower case.

However getESSList always returns the bound SN using forced upper case so it is impossible to query getESSList and obtain a list of correct SN to query using the other API calls.

Either getESSList should be made case sensitive so that it returns the correct case of the bound SN or every other API call should be made case insensitive so that they will work even if the SN is referenced using the incorrect case.

**Comment by ElevenFan** [comment]
OK，We Will check it @CharlesGillanders

**Comment by CharlesGillanders** [comment]
The behaviour I saw yesterday with case handling occurred around the same time as you fixed some other issues for people who had been reporting they were unable to remove and re-bind their inverters.

It's very possible that what I observed may have been incorrect or only temporary.

Hopefully it's easy to confirm if this is or is not an issue.

**Comment by ElevenFan** [comment]
It has been fixed
