### ISSUE TITLE
Extension of the API for Storion-S5 systems.

### ISSUE THREAD

**Issue by Joehne** [alphaess-developer/alphacloud_open_api#49]
The Storion-S5 model has not been taken into account in the API. This model does not transmit real-time data every 10 seconds like other systems. However, the Storion-S5 system transmits performance data such as for consumption, grid, modules and soc every 6 minutes.
Please extend the interface so that the 6-minute performance data of the Storion-S5 can be queried.

**Comment by ElevenFan** [comment]
Sorry，Not supported and not developed

**Comment by Joehne** [comment]
It was clear to me that it had not been developed, otherwise I would have found something in the API. My request was that the Strion system be included in the development plan. Why aren't all systems supported by Alphaess? Did I buy the system too early or wrong?

**Comment by ElevenFan** [comment]
It is recommended to contact our after-sales service to see if they have a solution.

**Comment by Joehne** [comment]
ok, do you have a contact person or an email address for me? Many thanks

**Comment by ElevenFan** [comment]
Submit multiple customer complaints in AlphaCloud and see how the after-sales service responds.
