### ISSUE TITLE
Server should be secured ASAP!

### ISSUE THREAD

**Issue by dehsgr** [alphaess-developer/alphacloud_open_api#5]
Currently open API uses unencrypted HTTP for transport (http://open.alphaess.com). You should add SSL certificate to that system ASAP and redirect all calls to HTTPS (https://open.alphaess.com), especially because there are data transferred such as credentials.

**Comment by ElevenFan** [comment]
I'm thinking about this too, but my Api is using https

**Comment by dehsgr** [comment]
Yes, of course, API is HTTPs. But regarding to European GPDR all sensitive data must be encrypted. You will provide mail address, password, tokens. All of them should be transferred protected. Otherwise there are too many problems regarding man-in-the-middel attacks. Further encrypted HTTP transport is state-of-the-art to day.

**Comment by ElevenFan** [comment]
Thanks，I will use https。https://open.alphaess.com

**Comment by dehsgr** [comment]
Great! Many thanks!
