### ISSUE TITLE
getSumDataForCustomer query not resetting for timezones outside of UTC

### ISSUE THREAD

**Issue by Poshy163** [alphaess-developer/alphacloud_open_api#50]
getSumDataForCustomer only resets the values returned by it when midnight UTC hits, as can be seens in this example

`2023-12-05 23:59:48.600 ... 'epvtoday': 18.3 ...`

Then once midnight locally hits, 

`2023-12-06 00:01:57.381 ... 'epvtoday': 18.3 ...`

This would occur later in the day for anyone forward of UTC, and early for anyone behind UTC, one solution may be implement a query date, and pass information based off of that date.

**Comment by Gaspode69** [comment]
I can confirm this issue.
Contrary to that, values returned by getOneDateEnergyBySn are reset correctly at 0:00 local time.
