### ISSUE TITLE
Fehler bei Aktivierung von Smile 5

### ISSUE THREAD

**Issue by juergenhaeg** [alphaess-developer/alphacloud_open_api#51]
Hallo,
ich bekomme meine Anlage nicht in der Entwicklungsumgebung hinzugefügt, "Der verbindliche sn-Autorisierungscode ist ungültig",
S/N und Check Code sind richtig eingegeben, was mache ich falsch? 
mfg
Jürgen

**Comment by ElevenFan** [comment]
I can't understand what is the problem?

**Comment by CharlesGillanders** [comment]
> I can't understand what is the problem?

He is unable to bind his inverter to his open api developer account.  He is getting an error about an invalid authorization code.

**Comment by ElevenFan** [comment]
In AlphaCloud, submit a customer complaint to retrieve it

**Comment by juergenhaeg** [comment]
I did that, but still no response :)
