### ISSUE TITLE
timestamp error

### ISSUE THREAD

**Issue by matt-oneill** [alphaess-developer/alphacloud_open_api#58]
after new year outage now getting a timestamp error.
`{"code":6009,"msg":"The request timestamp is not within the validity period"}`
I don't believe the library has changed since it was last working, also getting the same error from postman.
https://github.com/CharlesGillanders/alphaess/blob/ad97bf62f65f1a4329746d5722e1250f8e5ba921/alphaess/alphaess.py#L34C13-L34C13

**Comment by ElevenFan** [comment]
Share your code, hope someone can help you solve it。

**Comment by matt-oneill** [comment]
Its now working - whitelist had been enabled on my account (don't know how) 
Should the API return a more descriptive error message for this instead of the misleading timestamp message

**Comment by ElevenFan** [comment]
OK,Closed
