### ISSUE TITLE
Postman Collection

### ISSUE THREAD

**Issue by bnc-rainman** [alphaess-developer/alphacloud_open_api#6]
Not a Issue, but maybe it helps to develop. 

Attached a collection of all GET requests including a pre-request Script for automatic calculation the sign header (SHA512 header)

You need to create an environment and setup the vars AppID, AppSecret and SysSn.

[AlphaESS.postman_collection.json.zip](https://github.com/alphaess-developer/alphacloud_open_api/files/10764850/AlphaESS.postman_collection.json.zip)

**Comment by matt-oneill** [comment]
@bnc-rainman was just about to post the same thing. I can't get the posts working either with params or json body, how about you?

**Comment by bnc-rainman** [comment]
@matt-oneill  I don´t tried it yet. I will test it in the evening and write tommorow again.

**Comment by ElevenFan** [comment]
Thanks

**Comment by bnc-rainman** [comment]
@matt-oneill  It doesn`t work on my side too.

```
{
    "code": 6026,
    "data": null,
    "expMsg": null,
    "msg": "org.springframework.security.web.firewall.StrictHttpFirewall$StrictFirewalledRequest$1@c850997"
}
```

The return code 6026 is not listed in the documentation and the word "firewall" indicates to an environment problem in my mind.

**Comment by ElevenFan** [comment]
6026 means internal error，Which Api are you calling?

**Comment by bnc-rainman** [comment]
@ElevenFan 

https://openapi.alphaess.com/api/updateDisChargeConfigInfo

Parameters
- batUseCap: 15
- ctrDis: 0
- timeDise1: "00:00"
- timeDise2: "00:00"
- timeDisf1: "00:00"
- timeDisf2: "00:00"
- sysSn: ALxxx

**Comment by matt-oneill** [comment]
@ElevenFan I get the same error as above sending with parameters. 
I tried removing the parameters (just leaving sysSn) and passing the json body instead
```
{
  "batHighCap": 100,
  "gridCharge": 1,
  "timeChaf1": "00:30",
  "timeChae1": "04:30",
  "timeChaf2": "00:00",
  "timeChae2": "00:00",
}
```
and got the response
```
{
  "code": 6005,
  "data": null,
  "expMsg": null,
  "msg": null
}
```

hope that helps. 

All 'GET' endpoints are working nicely - Thanks!

**Comment by webenico** [comment]
I also receive the code 6026 but for the URL "https://openapi.alphaess.com/api/getOneDayPowerBySn"

**Comment by matt-oneill** [comment]
@webenico there’s 2 definitions for this in the documentation, you get an error if you dont send queryDate parameter

**Comment by webenico** [comment]
Thank you for your answer.

As I can see in the documentation for this request the only request paraterer needed is Syssn. However i provided queryDate too and also got the responsecode 6026.

**Comment by webenico** [comment]
I see, they provide the same request URL for "According SN to get real-time power data" and for "According SN to get system power data"

It worked now to get a result with Date. But I don't get a result without. According to the documentation I have expected to get the real time data without providing a date.

**Comment by ElevenFan** [comment]
We wrote the wrong Api address in English。

**Comment by ElevenFan** [comment]
issus closed
