### ISSUE TITLE
api/updateChargeConfigInfo returning 404 Not Found error

### ISSUE THREAD

**Issue by nugget100** [alphaess-developer/alphacloud_open_api#60]
Receiving 404 'Not Found' error when connecting to api/updateChargeConfigInfo endpoint

{'timestamp': '2024-01-05T08:20:11.954+00:00', 'status': 404, 'error': 'Not Found', 'path': '/api/updateChargeConfigInfo'}

This has been working fine up until about 5 days ago

**Comment by Gaspode69** [comment]
Additional hint:
As stated [here](https://github.com/alphaess-developer/alphacloud_open_api/issues/59#issuecomment-1878546976) this does not happen if an outdated timestamp is used. In this case the request is answered with error code 6006 (Timestamp Error).
However, if a valid request with the correct timestamp is sent, Error 404 'Not Found' is raised.

**Comment by ElevenFan** [comment]
We updated it and found a bug。Now you can try to test it。

**Comment by Gaspode69** [comment]
I can confirm that it is working now. Thanks.
