### ISSUE TITLE
Feature Request: Battery temperature

### ISSUE THREAD

**Issue by MrIcemanLE** [alphaess-developer/alphacloud_open_api#61]
Hi!

Do you plan to integrate the battery temperature (and maybe others too) in your API?
Whould be nice to get this information for my system.

Regards

**Comment by ElevenFan** [comment]
Please explain your usage scenario and purpose.

**Comment by MrIcemanLE** [comment]
The battery is mounted in a cold room with an electric heating. When the temp of the battery is getting to low i want to turn on a heater to keep the battery warm enough.

**Comment by ElevenFan** [comment]
@MrIcemanLE Please submit relevant requests to our after-sales service in our customer complaint system
