### ISSUE TITLE
Feature request: Set Pmeteroffset via API

### ISSUE THREAD

**Issue by robgunston** [alphaess-developer/alphacloud_open_api#63]
Please can we have the ability to set the Meter Offset Power(kW) settings via the API?

Our use case is when our factory load is very high and solar generation is low, we need to prioritise more grid power to preserve battery with a higher offset setting, and when production is low we would prioritise solar and battery with a lower offset setting. This is a setting we may want to change a number of times in a given day.

Screenshot shows the system setting on the website we'd like to control with the API - specifically the 'Meter Offset Power(kW)' value.

Thanks, Rob

![image](https://github.com/alphaess-developer/alphacloud_open_api/assets/40008413/59e89fb5-421b-49a5-a7f1-81265e061ffb)

**Comment by ElevenFan** [comment]
Industrial and commercial equipment is not supported yet

**Comment by robgunston** [comment]
Hi @ElevenFan thanks for the response. Do you know if there is a schedule for supporting this? We are able to use the API currently to monitor usage and trigger live alerts (e.g. low battery), but it would be awesome to be able to also control the system as outlined above.

**Comment by RizzoRat** [comment]
From what I know the device stores those settings in an EEPROM, which has a limited number of supported write actions. These memories usually support 10.000 only (before they "break", though some have 100.000), so changing settings too often will degrade lifetime noticeably. From that, I dare to guess it won't happen any soon

**Comment by ElevenFan** [comment]
@robgunston Please submit relevant requests to our after-sales service in our customer complaint system
