### ISSUE TITLE
Feature Request: Grid Feed-in Control

### ISSUE THREAD

**Issue by matt-oneill** [alphaess-developer/alphacloud_open_api#64]
Can you add new API to get & set Grid Feed in Function as per new functionality within the app

![IMG_5584](https://github.com/alphaess-developer/alphacloud_open_api/assets/60574293/ad650508-c59d-4533-ba93-8d8809b0ebad)
![IMG_5586](https://github.com/alphaess-developer/alphacloud_open_api/assets/60574293/1df3ea0a-d8ec-439f-bdb6-b73ddc42a20d)

**Comment by ElevenFan** [comment]
What do you want this API to do?

**Comment by matt-oneill** [comment]
> What do you want this API to do?

Similar to the API for getChargeConfigInfo and updateChargeConfigInfo.
this API should 
GET the current grid feed in config for the sysSn
POST update the grid feed in config for the sysSn

**Comment by ElevenFan** [comment]
I don't understand what this is trying to do?

**Comment by matt-oneill** [comment]
@ElevenFan what don't you understand?
What is the function doing in the mobile application?

**Comment by CadeusTheGreat** [comment]
Hello @ElevenFan this request is asking for developer API access to the grid feed-in control. This feature allows us to force discharge our batteries to the grid so that we can earn from exporting energy (i.e. storing power for peak rates where we can then dump the power). In the app/website which recently released this feature for some battery models; we have the ability to set how much power is discharged at set times with a battery cut-off that will stop exporting when it reaches that set SoC %.

What we are looking for is API access to this feature so that we can integrate it into our external applications i.e. Home Assistant.
Thank you.

**Comment by ElevenFan** [comment]
@matt-oneill @CadeusTheGreat This API has not been notified yet. If necessary, please contact our local after-sales team.Thanks~

**Comment by matt-oneill** [comment]
> @matt-oneill @CadeusTheGreat This API has not been notified yet. If necessary, please contact our local after-sales team.Thanks~

I don't know what you mean by it has not been notified, its in the app

**Comment by ElevenFan** [comment]
I am a developer, not a product, and I do not have permission to add new APIs.

**Comment by matt-oneill** [comment]
@ElevenFan might be lost in translation, this is not a request for a new api.
The api is existing in the current apps, and I'm suggesting to add it to the open api. After all, the open api was created so that people weren't scraping the official api?

Here's an example of the official api calls if that helps

POST: https://cloud.alphaess.com/api/base/sysSet/saveFeedStrategy
BODY:
```
{
    "batteryEn":1,
    "batteryFeedCutoffSoc":50,
    "id":"xxxxxxxxxxxxxxxxxxx",
    "feedStrategyDTOList": [
        {
            "id":9999,
            "sysSn":"ALXXXXXXXXXXXXX",
            "start":"16:00",
            "end":"19:00",
            "feedPower":3000,
            "sort":1
        }
    ]
}
```
RESPONSE:
```
{
    "code":200,
    "msg":"Success",
    "expMsg":null,
    "data":true,
    "extra":null
}
```

GET: https://cloud.alphaess.com/api/base/sysSet/getFeedStrategyList?id=xxxxxxxxxxxxxxxxxxx
RESPONSE:
```
{
    "code": 200,
    "msg": "Success",
    "expMsg": null,
    "data": {
        "batteryEn": 1,
        "batteryFeedCutoffSoc": 50.00,
        "poinv": 3000.00,
        "timePeriodLimit": 6,
        "batUseCap": 10.00,
        "feedStrategyVOList": [
            {
                "id": 9999,
                "sysSn": "ALXXXXXXXXXXXXX",
                "start": "16:00",
                "end": "19:00",
                "feedPower": 3000,
                "sort": 1
            }
        ]
    },
    "extra": null
}
```

**Comment by ElevenFan** [comment]
Do not use the web platform API？

**Comment by matt-oneill** [comment]
@ElevenFan any plans to add the grid feed in control to the open api? or is this only available on the official api?

I have automations to set the battery charge settings based on other parameters (solar forecast, current import/export rates, battery state etc) so to be able to set the grid feed in will complete this functionality
