### ISSUE TITLE
Feature Request: Set EV-Charging Mode

### ISSUE THREAD

**Issue by mapo-89** [alphaess-developer/alphacloud_open_api#66]
Can you add to the API to get & set EV-Charging Mode Function as in the app
![image](https://github.com/alphaess-developer/alphacloud_open_api/assets/118180259/cb919139-a3d8-4c2c-bc2f-20b8dd9b68c4)

**Comment by Poshy163** [comment]
No, we can only do what's given to us VIA the official API

**Comment by Rasenkardinal** [comment]
+1

**Comment by Rasenkardinal** [comment]
This is essential. Please add!

**Comment by ElevenFan** [comment]
@mapo-89 Please submit relevant requests to our after-sales service in our customer complaint system

**Comment by akassa89** [comment]
@ElevenFan @mapo-89 any updates?
