### ISSUE TITLE
Not able to register to open API because of SN / checkcode not working

### ISSUE THREAD

**Issue by civi801** [alphaess-developer/alphacloud_open_api#67]
Hi,

sorry about opening an issue here as I guess the issue should be resolved by AlphaESS directly, but I was send by their support team here:

> AGSS-TSC Public
> 2024-03-04 10:35:31
> Hallo
> In Bezug auf das OpenApi-Problem können Sie direkt Feedback in der GitHub-Community geben, und professionelles Personal wird es basierend auf Ihrem Feedback behandeln.
> Wenn Sie weitere Fragen haben, können Sie eine neue Beschwerde erstellen, um uns Feedback zu geben. Vielen Dank für Ihre Mitarbeit. Danke!

I have the same issue described here already: [(https://github.com/alphaess-developer/alphacloud_open_api/issues/7)]
My serial number used on the normal monitoring portal is different than the one on the sticker with the check code, so I cannot register the system on the open api portal. The number on the monitoring portal is the same that is reported by the device when checking the display.

I have a Smile 5 like the others and there is no additional sticker inside the cover below the converter. 

I filed three tickets on the AlphaESS portal already with references to the ticket above, and also tried to get the additional code from the company installing the system with no luck.

Is there a way to get the check code for my serial number so I can register?

Thanks a lot in advance!
Chris

**Comment by CharlesGillanders** [comment]
Yeh I have no idea why Alpha would refer you here!?  The only people who can make any change to their OpenAPI registration is themselves.  I'm guessing they are confused because you are using this integration but if the problem is the OpenAPI then it doesn't matter what integration you are using - you need to get registered to their portal first.

**Comment by ElevenFan** [comment]
Please submit a customer complaint and our after-sales service will help you retrieve it.
