### ISSUE TITLE
Cannot register my battery, invalid check code

### ISSUE THREAD

**Issue by IAmKonni** [alphaess-developer/alphacloud_open_api#7]
I can not register my battery. It says that my check code must consist of numbers and characters, not longer than 10 digits.

My check code is a number with 6 digits and seems not to be recognized as a valid number.

![image](https://user-images.githubusercontent.com/67658239/219870314-7807604f-02f7-4044-9a95-71a942728e0d.png)

Thank you in advance and with regards
Konni

**Comment by dehsgr** [comment]
Which system type are you using? I ran in this issue too. Later then I recognized there were two check codes on my system. One outside (this failed) and one behind the cover below the inverter (Smile T10). You must use the check code listed directly below the serial you posted above.

**Comment by IAmKonni** [comment]
It's a Smile B3. I took both SN and check code from the outer left side of the device.
SN fits to the SN in the monitoring portal.

**Comment by dehsgr** [comment]
You might check to remove the cover of the control unit and see if there is another check code. This should be the right one.

**Comment by Gaspode69** [comment]
I have exactly the same problem (Smile 5).
The SN is correct, but the check code is not accepted, same behavior as described by @IAmKonni above.

**Comment by ElevenFan** [comment]
Abount this question，If you do not know your CheckCode, please submit a customer complaint, and we after the sale will help you find it  。

**Comment by ElevenFan** [comment]
@IAmKonni Did you find the CheckCode?

**Comment by IAmKonni** [comment]
I did not find any other check code on the device without opening it.
I opened an issue in the costumer complaints system in the monitoring portal to receive help.

**Comment by Gaspode69** [comment]
@ElevenFan 
To clarify: The problem is not, that some of us do not find the check code. The problem is, that the check code, which can be found on the Alpha-ESS device is not accepted, even though the correct serial number can be read above the check code.
Can you please check if probably older models like Smile 5 and B3 have been "forgotten" to handle?

**Comment by ElevenFan** [comment]
No, because the installer needs to use CheckCode and SN to install the equipment, and CheckCode is more critical。

**Comment by Gaspode69** [comment]
@ElevenFan 
Sorry, what do you mean with "no"?
As written above, on my Smile 5 there is a sticker on it with SN and check code. The SN fits to the SN in the Alpha ESS cloud portal. However, the check code is not accepted by open.alpha-ess.com

**Comment by ElevenFan** [comment]
If there is no verification code and SN is bound, there is only SN, and anyone can bind SN to send a verification code to all device owners through a script. this is a security issue。

**Comment by IAmKonni** [comment]
We all have a check code on our devices. But the check code is not accepted by the registration web form, as it says it would be invalid.

**Comment by Gaspode69** [comment]
> Abount this question，If you do not know your CheckCode, please submit a customer complaint, and we after the sale will help you find it 。

Answer from customer support:
Sehr geehrte Kunde/Kundin,
vielen Dank für Ihr Feedback.
Die Website https://open.alphaess.com befindet sich noch in Entwicklung und Testen. 
Wenn Sie noch Fragen haben, wäre es sehr nett von Ihnen,  ein neues Ticket zu erstellen! Bei weiteren Anliegen stehen wir Ihnen zur Verfügung. Für eine Bewertung bedanken wir uns herzlich!
Mit freundlichen Grüßen
XXXXX
Technisches Service

With other words: They do not feel responsible.

**Comment by ElevenFan** [comment]
Today I Update it,I Find a bug, Now you can try to bind it.

**Comment by ElevenFan** [comment]
@Gaspode69

**Comment by IAmKonni** [comment]
It works now - thank you.
