### ISSUE TITLE
Feature Request: Set AUX Contact Setting

### ISSUE THREAD

**Issue by mapo-89** [alphaess-developer/alphacloud_open_api#71]
Can you add to the API to get & set AUX Contact Setting as in the app
![Screenshot_20240430-204024~2](https://github.com/alphaess-developer/alphacloud_open_api/assets/118180259/df454172-5958-4b02-88bd-7b1a86463e03)

![Screenshot_20240430-204140](https://github.com/alphaess-developer/alphacloud_open_api/assets/118180259/cfb28616-2590-464f-b0f7-36862a2df583)

**Comment by ElevenFan** [comment]
@mapo-89 Please submit relevant requests to our after-sales service in our customer complaint system
