### ISSUE TITLE
Price upload

### ISSUE THREAD

**Issue by HITESHLAD1985** [alphaess-developer/alphacloud_open_api#74]
Hi sorry this is not a problem but not sure where to ask for developments. Is it possible to have an API to send the price of electric to the application. For example I have daily price changes and have to manually change the price each day.

**Comment by ElevenFan** [comment]
What do you want this for?

**Comment by HITESHLAD1985** [comment]
So I can feed in the daily electric prices ever day or every 30 min. Octopus energy have tariffs that changes every day or every 30 min. Currently we have to do this manually.
