### ISSUE TITLE
Making API documentation publically available

### ISSUE THREAD

**Issue by samharrison7** [alphaess-developer/alphacloud_open_api#75]
Hello,

I have just started using the AlphaESS API. I wanted to use it on the Python hosting service [PythonAnyhwere](https://www.pythonanywhere.com/), but their free accounts only allow connections to whitelisted domains, and open.alphaess.com isn't on the list.

I have been in contact with PythonAnywhere, and they have confirmed that they will only add AlphaESS to the whitelisted domain if there is *public* documentation for the API. Unfortunately, the fact that you have to login via open.alphaess.com means they won't class the documentation as public and therefore won't whitelist the domain.

I was wondering whether there was any scope for AlphaESS to add the documentation to a public-facing part of their website, instead of requiring users to have an account?

Cheers,
Sam

**Comment by ElevenFan** [comment]
No plans yet
