### ISSUE TITLE
Open API access very instable

### ISSUE THREAD

**Issue by Gaspode69** [alphaess-developer/alphacloud_open_api#78]
Hi,
recently, accessing the Alpha-ESS OpenAPI got very instable. I get timeouts very often.
Is there a known problem?
For example, today the problems started at 1 pm CEST and are currently ongoing.
Thanks
Gaspode

**Comment by CharlesGillanders** [comment]
Can you paste the error you are seeing?  Just as an anecdote I’m not seeing any errors or instability with my own Alpha unit.

**Comment by Gaspode69** [comment]
No specific error, just timeouts accessing openAPI Region: Germany

**Comment by CharlesGillanders** [comment]
Is there an error on that mentions timeout?  I  trying to figure out if the timeout is being reported by the integration or by the API library code or by some other part of home assistant. Something must be giving you a timeout response, it would help if I knew where that was coming from.

**Comment by Gaspode69** [comment]
I use Axios in node.js.
A timeout error usually means that the host is currently not reachable.

**Comment by Poshy163** [comment]
I've personally not had any issues here, some sort of DNS issue on your end?

**Comment by Gaspode69** [comment]
> I've personally not had any issues here, maybe some sort of DNS issue on your end?

Can't beleive it. issue starts suddenly and ends a few hours later. In between some requests are answered, some not (timeout).

@Poshy163 
In which part of the world are you?

@ElevenFan 
Do you have an idea what might be wrong?

**Comment by ElevenFan** [comment]
I didn't find any problem, could you please send  the result?

**Comment by Gaspode69** [comment]
@ElevenFan 
> I didn't find any problem, could you please send the result?

`AxiosError: timeout of 10000ms exceeded`
