### ISSUE TITLE
pBat value

### ISSUE THREAD

**Issue by webenico** [alphaess-developer/alphacloud_open_api#8]
Hi,

It would be helpful if the pBat value would be positiv or nefativ depending on charge or discharge the battery. 
(like pGrid)

Is this possible?

Thanks,
Nico

**Comment by ElevenFan** [comment]
@webenico

**Comment by dehsgr** [comment]
@ElevenFan shouldn't it be vice-versa (discharge negative; charge positive)? Would make more sense for me.

**Comment by Gaspode69** [comment]
@dehsgr 
I don't think so. The current inofficial API also handles charging as negative and discharging (=taking energy from Bat) as positive.
It is consistent with pGrid (positive = taking energy from grid) and ppv (always positive). The sum of the three values (ppv+pGrid+pBat results in the current consumption)

**Comment by ElevenFan** [comment]
Is there a more reasonable way to tell you to charge or discharge?

**Comment by zuehlke-dea** [comment]
I would also second this. I started yesterday using the API and would be glad if this changes

**Comment by Gaspode69** [comment]
> Yes。A negative value means charging, a positive value means discharging, and 0 means no charging.

Just for the records: Currently, pBat is always positive, independently if the battery is charged or discharged.

**Comment by webenico** [comment]
Same for me. pBat is currently always positive.

**Comment by ElevenFan** [comment]
![image](https://user-images.githubusercontent.com/117050711/221800083-141cfabb-442a-42e7-8053-b4fe48bfb1fa.png)
@webenico @Gaspode69 @zuehlke-dea Our Program is update.Please try to test it.Thanks~~

**Comment by ElevenFan** [comment]
A positive value of pbat indicates that the battery is discharging, and a negative value indicates that the battery is charging.

**Comment by Gaspode69** [comment]
@ElevenFan 
Thanks for the update. I can confirm that now pBat is negative when charging battery.

**Comment by ElevenFan** [comment]
Close issues
