### ISSUE TITLE
Feed-in Control API

### ISSUE THREAD

**Issue by tonbut** [alphaess-developer/alphacloud_open_api#81]
Hi, i'm finding the API really useful but it is missing an API call for reading/writing the feed-in control function available on Smile5. 

I'd love for that to be on the roadmap so that it can be programatically controlled and not just from the App.

Thanks for your consideration, Tony

**Comment by ElevenFan** [comment]
Suggest to contact us after-sales。

**Comment by ElevenFan** [comment]
Please contact us after-sales。
