### ISSUE TITLE
getSumDataForCustomer returns 0 for all 'today' values

### ISSUE THREAD

**Issue by Gaspode69** [alphaess-developer/alphacloud_open_api#82]
Hi @ElevenFan 

since a short time (at least one day, maybe longer) getSumDataForCustomer returns 0 for all 'today' values, i.e.

- epvtoday
- todayIncome
- eoutput
- einput
- echarge
- edischarge

Can you please check what's going on?

**Comment by Poshy163** [comment]
Seems to be the case of ~24 hours ago, also the response time to the API is ridiculous (like 18s)

![image](https://github.com/user-attachments/assets/45da2f5d-367f-439c-a0c6-1c0b65e221ff)

**Comment by ElevenFan** [comment]
Our server group is handling this issue, it is not an API program problem. @Gaspode69 @Poshy163

**Comment by Poshy163** [comment]
@ElevenFan Thanks for that update, is there any sort of update on when the values for getSumDataForCustomer will stop returning 0, rather the actual value?

**Comment by ElevenFan** [comment]
Suggest to contact us after-sales

**Comment by Gaspode69** [comment]
@ElevenFan 
> Suggest to contact us after-sales

Sorry? we are talking about documented return values in the Open API, see here:

https://open.alphaess.com/developmentManagement/apiList
Chapter "According SN to get System Summary data"

Why should we contact aftersales? It is obvious, that the APi does not work as documented.

Three days ago the values vere delivered as documented.

**Comment by Menschomat** [comment]
@Gaspode69 it's definetly their API-Layer/Backend... We are experiencing the same problems.

**Comment by ElevenFan** [comment]
Fixed it

**Comment by Gaspode69** [comment]
Thank you @ElevenFan 

Works again :-)

**Comment by Poshy163** [comment]
.... 
<img width="283" alt="Screenshot 2024-09-04 at 5 32 44 pm" src="https://github.com/user-attachments/assets/778d716b-1b28-40f5-b86f-68759cb8dd42">

**Comment by ElevenFan** [comment]
@Poshy163 Please log in to Slack. I need to know your SN

**Comment by Meigl89** [comment]
I'm new to this so I hope I can also deliver some informations. On my end it's also still "0" for the entity total_load:

![image](https://github.com/user-attachments/assets/079c9ad3-ba4b-4899-b3e3-047484d12fd0)

**Comment by Poshy163** [comment]
Yeah, it just happened again. issue on their end. ElevenFan seems to be looking into it?

**Comment by Gaspode69** [comment]
I'm still facing these issues.

**Comment by Meigl89** [comment]
Same here, dashboard still bogus.

**Comment by gospelrock** [comment]
Now it works.  👍

**Comment by Meigl89** [comment]
Now I have also some changes for the total load entity:

![image](https://github.com/user-attachments/assets/894ffe29-46ee-4b0d-b0d1-ba155be2a58f)

Energy dashboard still more then reality, let's see tomorrow.

**Comment by Gaspode69** [comment]
@Meigl89 
It makes no sense to post dashboards from whatever Applikation. We need the reference to OpenAPI
As far as I can see, the values are OK again. I'll check more carrfully tomorrow.

**Comment by Gaspode69** [comment]
@ElevenFan 
So far as I can see the values are correct again. Thank you!
