### ISSUE TITLE
SQL Error with updateChargeConfigInfo and updateDisChargeConfigInfo

### ISSUE THREAD

**Issue by matt-oneill** [alphaess-developer/alphacloud_open_api#83]
All GET endpoints are working ok, but the endpoints to set Charge and Discharge config are returning a SQL error.
Http response code is 200, but the response body has the error:
`{
    "code": 6026,
    "msg": "network is busy",
    "expMsg": "\n### Error updating database.  Cause: java.sql.SQLException: TDengine ERROR (0x2603): Table does not exist\n### The error may exist in com/alphaess/api/mapper/SysUserLogMapper.java (best guess)\n### The error may involve com.alphaess.api.mapper.SysUserLogMapper.insert-Inline\n### The error occurred while setting parameters\n### SQL: INSERT INTO sys_user_log  ( sys_sn, log_content, createtime, log_from, log_type, operator )  VALUES  ( ?, ?, ?, ?, ?, ? )\n### Cause: java.sql.SQLException: TDengine ERROR (0x2603): Table does not exist\n; uncategorized SQLException; SQL state []; error code [9731]; TDengine ERROR (0x2603): Table does not exist; nested exception is java.sql.SQLException: TDengine ERROR (0x2603): Table does not exist",
    "data": null,
    "extra": null
}`

**Comment by ElevenFan** [comment]
Please contact us after-sales。
