### ISSUE TITLE
Disabling grid charge via updateChargeConfigInfo results in error 6053

### ISSUE THREAD

**Issue by dehsgr** [alphaess-developer/alphacloud_open_api#84]
Trying to disable grid charge via updateChargeConfigInfo results in the following error:

> The maximum number of requests has been reached (6053)

Payload for disabling grid charge is:

```
{
    "sysSn": "PLACEYOURSERIALHERE",
    "gridCharge": 0,
    "timeChaf1": "00:00",
    "timeChae1": "00:00",
    "timeChaf2": "00:00",
    "timeChae2": "00:00",
    "batHighCap": 100
}
```

**Comment by ElevenFan** [comment]
Please contact us after-sales。

**Comment by dehsgr** [comment]
Hi @ElevenFan,

I don‘t See why I should contact After-Sales for a Bug in this API?! I would like you to clarify. This is a documented function from your API and should work accordingly.

Kind regards!
