### ISSUE TITLE
Server returning 500 when requesting verification code

### ISSUE THREAD

**Issue by Bickio** [alphaess-developer/alphacloud_open_api#87]
![image](https://github.com/user-attachments/assets/67733a21-2891-4d44-a7d9-e04ee5b23150)

Repro steps:

- https://open.alphaess.com/developmentManagement/developerInformation
- Click "Add"
- Enter system S/N and CheckCode
- Click "Get Verification Code"

Result:
- (See image above)
- No email
- HTTP response 500 in browser networking tab

**Comment by ShaneO68atgmail** [comment]
I have the exact same issue

**Comment by rninne** [comment]
Following as I'm also having this issue trying to register an inverter.

**Comment by Bickio** [comment]
@ElevenFan Perhaps you know if there's a better support channel for this?

**Comment by ElevenFan** [comment]
Please contact us after-sales。

**Comment by Bickio** [comment]
Initial response from customer service:

> Please be assured that we have informed our relevant team and are actively working to resolve this issue for you

Will update here if/when I hear more
