### ISSUE TITLE
AlphaESS Platform Update Notice

### ISSUE THREAD

**Issue by ElevenFan** [alphaess-developer/alphacloud_open_api#88]
AlphaESS Platform Update Notice: We will be performing maintenance on the AlphaESS platform on October 12, 2024, from 13:00 to 18:00 (UTC+8). During this time, we'll be launching the Multi-Data Center feature. You may experience some login instability or might not be able to log in. After the maintenance, AlphaESS App versions 5.0 and below will no longer be supported. To ensure you have the best experience, we strongly recommend upgrading your AlphaESS App to the latest version as soon as possible. The new version will offer a more stable and smoother experience. Thank you for your understanding and support!

**Comment by dan-s-github** [comment]
It seems that the maintenance is ongoing as I am not able to login into [cloud.alphaess](https://cloud.alphaess.com)

Is there a system status page available to check if it should be back online?

**Comment by Poshy163** [comment]
@dan-s-github 
![image](https://github.com/user-attachments/assets/1d1f9d7f-3fe7-4274-8b72-84fefcb28053)

**Comment by dan-s-github** [comment]
System was back accessible through API at 9AM GMT+13, could now also login to cloud.alphaess.com and saw the maintenance announcement for today

**Comment by tbgoose** [comment]
> System was back accessible through API at 9AM GMT+13, could now also login to cloud.alphaess.com and saw the maintenance announcement for today

So is everything working for you? Alpha monitoring app still shows no data for me, and can't access anything through cloud api (can log in but postman doesn't return values). Obviously home assistant integration has ceased working (actually stopped for me on 10th...)

**Comment by dan-s-github** [comment]
system was back online for a while yesterday and cloud.alphaess.com ad app shows maintenance mode. 

Last message from HA Integration is
<img width="304" alt="image" src="https://github.com/user-attachments/assets/4a1deef3-68a6-440a-92a3-db8049b3aecd">
