### ISSUE TITLE
The problem is still being processed. If you have any questions, please contact alpha after-sales service.

### ISSUE THREAD

**Issue by ElevenFan** [alphaess-developer/alphacloud_open_api#89]
The problem is still being processed. If you have any questions, please contact alpha after-sales service.

**Comment by sukitha722002** [comment]
@ElevenFan Thanks. I'm hoping you can fix the API soon. Currently getting 500 internal server error message.

**Comment by HeinMueck01** [comment]
Still receiving following failure: "There was an error communicating with Alpha Services: Error: Client network socket disconnected before secure TLS connection was established (0)"  and "There was an error communicating with Alpha Services: AxiosError: Request failed with status code 500 (0)". The node-red-contrib-alphaess 2.0.2 was running more than 8 month without problems until the AlphaCloud System Update last week. What can be done?

**Comment by dehsgr** [comment]
@HeinMueck01 I think we‘ve to wait…

**Comment by Liberty-clouds** [comment]
> Still receiving following failure: "There was an error communicating with Alpha Services: Error: Client network socket disconnected before secure TLS connection was established (0)" and "There was an error communicating with Alpha Services: AxiosError: Request failed with status code 500 (0)". The node-red-contrib-alphaess 2.0.2 was running more than 8 month without problems until the AlphaCloud System Update last week. What can be done?

Can you provide a specific link address or interface address to facilitate our investigation?

**Comment by HeinMueck01** [comment]
I'm using Node-Red the node-red-contrib-alphaess in Version 2.0.2. Was all the time working perfect, problems arrise after last AlphaCloud Update. Now some values comming back slowly. Here the debug message, as you can see the values are not the same:
![alphaess-app](https://github.com/user-attachments/assets/d015568a-e120-4dd0-8fcb-f370f2e3e624)


{"consumption":0,"grid":0,"modules":0,"battery":{"soc":0,"load":0},"today":{"consumption":7.57,"grid":{"supply":0.04,"purchase":4.41},"modules":3.3,"battery":{"charge":1.3,"discharge":1.6}},"rawdata":{"realtime":{"ppv":null,"ppvDetail":null,"soc":null,"pev":null,"pevDetail":null,"prealL1":null,"prealL2":null,"prealL3":null,"pbat":null,"pgridDetail":null,"pgrid":null,"pload":null},"statistics":{"hourly":[{"sysSn":"AL400************68","uploadTime":"2024-10-16 00:01:53","ppv":-8,"load":990,"cbat":34.4,"feedIn":0,"gridCharge":58,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 00:06:54","ppv":-8,"load":951,"cbat":32.8,"feedIn":1,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 00:11:55","ppv":-8,"load":563,"cbat":32.4,"feedIn":39,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 00:16:56","ppv":-8,"load":383,"cbat":32,"feedIn":0,"gridCharge":7,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 00:21:57","ppv":-8,"load":331,"cbat":32,"feedIn":0,"gridCharge":11,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 00:26:57","ppv":-8,"load":417,"cbat":31.2,"feedIn":0,"gridCharge":61,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 00:31:58","ppv":-8,"load":392,"cbat":31.2,"feedIn":0,"gridCharge":23,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 00:36:59","ppv":-8,"load":487,"cbat":30,"feedIn":194,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 00:41:59","ppv":-8,"load":407,"cbat":29.2,"feedIn":51,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 00:47:00","ppv":-8,"load":896,"cbat":28.4,"feedIn":0,"gridCharge":267,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 00:52:01","ppv":-8,"load":775,"cbat":26.8,"feedIn":8,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 00:57:02","ppv":-8,"load":465,"cbat":26,"feedIn":0,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 01:02:02","ppv":-8,"load":694,"cbat":25.2,"feedIn":0,"gridCharge":168,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 01:07:03","ppv":-8,"load":346,"cbat":24.8,"feedIn":114,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 01:12:04","ppv":-8,"load":261,"cbat":24.4,"feedIn":0,"gridCharge":3,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 01:17:05","ppv":-8,"load":255,"cbat":24.4,"feedIn":0,"gridCharge":2,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 01:22:05","ppv":-8,"load":262,"cbat":23.2,"feedIn":131,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 01:27:06","ppv":-8,"load":260,"cbat":22.4,"feedIn":0,"gridCharge":6,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 01:32:06","ppv":-8,"load":261,"cbat":21.2,"feedIn":0,"gridCharge":5,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 01:37:07","ppv":-8,"load":639,"cbat":19.6,"feedIn":17,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 01:42:08","ppv":-8,"load":360,"cbat":18,"feedIn":11,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 01:47:09","ppv":-8,"load":436,"cbat":17.6,"feedIn":36,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 01:52:10","ppv":-8,"load":367,"cbat":17.6,"feedIn":1,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 01:57:11","ppv":-8,"load":491,"cbat":16.8,"feedIn":43,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 02:02:12","ppv":-8,"load":477,"cbat":15.2,"feedIn":23,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 02:07:12","ppv":-8,"load":472,"cbat":14.8,"feedIn":2,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 02:12:13","ppv":-8,"load":477,"cbat":14,"feedIn":59,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 02:17:14","ppv":-8,"load":411,"cbat":13.6,"feedIn":43,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 02:22:14","ppv":-8,"load":334,"cbat":13.6,"feedIn":15,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 02:27:15","ppv":-8,"load":339,"cbat":13.6,"feedIn":49,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 02:32:16","ppv":-8,"load":718,"cbat":13.6,"feedIn":0,"gridCharge":6,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 02:37:16","ppv":-8,"load":326,"cbat":12.8,"feedIn":0,"gridCharge":15,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 02:42:17","ppv":-8,"load":630,"cbat":12.8,"feedIn":0,"gridCharge":253,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 02:47:17","ppv":-8,"load":362,"cbat":12.8,"feedIn":176,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 02:52:18","ppv":-8,"load":412,"cbat":12.4,"feedIn":17,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 02:57:19","ppv":-8,"load":778,"cbat":11.6,"feedIn":0,"gridCharge":786,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 03:02:19","ppv":-8,"load":407,"cbat":11.6,"feedIn":0,"gridCharge":415,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 03:07:20","ppv":-8,"load":487,"cbat":11.6,"feedIn":0,"gridCharge":495,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 03:12:21","ppv":-8,"load":2035,"cbat":11.6,"feedIn":0,"gridCharge":2043,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 03:17:21","ppv":-8,"load":532,"cbat":11.6,"feedIn":0,"gridCharge":540,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 03:22:22","ppv":-8,"load":503,"cbat":11.6,"feedIn":0,"gridCharge":511,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 03:27:22","ppv":-8,"load":540,"cbat":11.6,"feedIn":0,"gridCharge":548,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 03:32:23","ppv":0,"load":479,"cbat":11.6,"feedIn":0,"gridCharge":479,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 03:37:24","ppv":0,"load":517,"cbat":11.6,"feedIn":0,"gridCharge":517,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 03:42:24","ppv":-8,"load":405,"cbat":11.6,"feedIn":0,"gridCharge":413,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 03:47:25","ppv":0,"load":412,"cbat":11.6,"feedIn":0,"gridCharge":412,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 03:52:26","ppv":-8,"load":715,"cbat":11.6,"feedIn":0,"gridCharge":723,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 03:57:26","ppv":-8,"load":355,"cbat":11.6,"feedIn":0,"gridCharge":363,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 04:02:27","ppv":0,"load":420,"cbat":11.6,"feedIn":0,"gridCharge":420,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 04:07:28","ppv":-8,"load":409,"cbat":11.6,"feedIn":0,"gridCharge":417,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 04:12:28","ppv":-8,"load":408,"cbat":11.6,"feedIn":0,"gridCharge":416,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 04:17:29","ppv":-8,"load":413,"cbat":11.6,"feedIn":0,"gridCharge":421,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 04:22:30","ppv":-8,"load":459,"cbat":11.6,"feedIn":0,"gridCharge":467,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 04:27:31","ppv":-8,"load":412,"cbat":11.6,"feedIn":0,"gridCharge":420,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 04:32:32","ppv":-8,"load":644,"cbat":11.6,"feedIn":0,"gridCharge":652,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 04:37:33","ppv":-8,"load":438,"cbat":11.6,"feedIn":0,"gridCharge":446,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 04:42:34","ppv":-8,"load":427,"cbat":11.6,"feedIn":0,"gridCharge":435,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 04:47:35","ppv":-8,"load":429,"cbat":11.6,"feedIn":0,"gridCharge":437,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 04:52:36","ppv":-8,"load":470,"cbat":11.6,"feedIn":0,"gridCharge":478,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 04:57:37","ppv":-8,"load":478,"cbat":11.6,"feedIn":0,"gridCharge":486,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 05:02:38","ppv":-8,"load":463,"cbat":11.6,"feedIn":0,"gridCharge":471,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 05:07:39","ppv":-8,"load":522,"cbat":11.6,"feedIn":0,"gridCharge":530,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 05:12:40","ppv":-8,"load":535,"cbat":11.6,"feedIn":0,"gridCharge":543,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 05:17:41","ppv":-8,"load":799,"cbat":11.6,"feedIn":0,"gridCharge":807,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 05:22:41","ppv":-8,"load":1002,"cbat":11.6,"feedIn":0,"gridCharge":1010,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 05:27:42","ppv":-8,"load":654,"cbat":11.6,"feedIn":0,"gridCharge":662,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 05:32:42","ppv":-8,"load":599,"cbat":11.6,"feedIn":0,"gridCharge":607,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 05:37:43","ppv":-8,"load":385,"cbat":11.6,"feedIn":0,"gridCharge":393,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 05:42:44","ppv":-8,"load":434,"cbat":11.6,"feedIn":0,"gridCharge":442,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 05:47:45","ppv":-8,"load":423,"cbat":11.6,"feedIn":0,"gridCharge":431,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 05:52:45","ppv":-8,"load":428,"cbat":11.6,"feedIn":0,"gridCharge":436,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 05:57:46","ppv":-8,"load":416,"cbat":11.6,"feedIn":0,"gridCharge":424,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 06:02:47","ppv":-8,"load":416,"cbat":11.6,"feedIn":0,"gridCharge":424,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 06:07:48","ppv":-8,"load":408,"cbat":11.6,"feedIn":0,"gridCharge":416,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 06:12:50","ppv":-8,"load":1103,"cbat":11.6,"feedIn":0,"gridCharge":1111,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 06:17:51","ppv":-8,"load":602,"cbat":11.6,"feedIn":0,"gridCharge":610,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 06:22:51","ppv":-8,"load":918,"cbat":11.6,"feedIn":0,"gridCharge":926,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 06:27:51","ppv":-8,"load":976,"cbat":11.6,"feedIn":0,"gridCharge":984,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 06:32:52","ppv":0,"load":614,"cbat":11.6,"feedIn":0,"gridCharge":614,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 06:37:53","ppv":-8,"load":890,"cbat":11.6,"feedIn":0,"gridCharge":898,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 06:42:54","ppv":-8,"load":595,"cbat":11.6,"feedIn":0,"gridCharge":603,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 06:47:55","ppv":-8,"load":521,"cbat":11.6,"feedIn":0,"gridCharge":529,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 06:52:56","ppv":0,"load":536,"cbat":11.6,"feedIn":0,"gridCharge":536,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 06:57:57","ppv":-8,"load":506,"cbat":11.6,"feedIn":0,"gridCharge":514,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 07:02:59","ppv":-8,"load":496,"cbat":11.6,"feedIn":0,"gridCharge":504,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 07:07:59","ppv":-8,"load":496,"cbat":11.6,"feedIn":0,"gridCharge":504,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 07:13:00","ppv":-8,"load":744,"cbat":11.6,"feedIn":0,"gridCharge":752,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 07:18:01","ppv":-8,"load":441,"cbat":11.6,"feedIn":0,"gridCharge":449,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 07:23:02","ppv":-8,"load":2595,"cbat":11.6,"feedIn":0,"gridCharge":2603,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 07:28:07","ppv":-8,"load":444,"cbat":11.6,"feedIn":0,"gridCharge":452,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 07:33:07","ppv":-7,"load":520,"cbat":11.6,"feedIn":0,"gridCharge":527,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 07:38:08","ppv":-8,"load":2620,"cbat":11.6,"feedIn":0,"gridCharge":2628,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 07:43:09","ppv":-6,"load":2870,"cbat":11.6,"feedIn":0,"gridCharge":2876,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 07:48:10","ppv":-4,"load":466,"cbat":11.6,"feedIn":0,"gridCharge":470,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 07:53:11","ppv":-10,"load":868,"cbat":11.6,"feedIn":0,"gridCharge":878,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 07:58:12","ppv":-8,"load":531,"cbat":11.6,"feedIn":0,"gridCharge":539,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 08:03:13","ppv":-5,"load":2508,"cbat":11.6,"feedIn":0,"gridCharge":2513,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 08:08:14","ppv":-5,"load":2503,"cbat":11.6,"feedIn":0,"gridCharge":2508,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 08:13:15","ppv":85,"load":455,"cbat":11.6,"feedIn":0,"gridCharge":370,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 08:18:16","ppv":127,"load":741,"cbat":11.6,"feedIn":0,"gridCharge":614,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 08:23:17","ppv":179,"load":442,"cbat":11.6,"feedIn":0,"gridCharge":263,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 08:28:17","ppv":229,"load":413,"cbat":11.6,"feedIn":0,"gridCharge":184,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 08:33:19","ppv":253,"load":474,"cbat":11.6,"feedIn":0,"gridCharge":221,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 08:38:19","ppv":295,"load":486,"cbat":11.6,"feedIn":0,"gridCharge":191,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 08:43:20","ppv":359,"load":457,"cbat":11.6,"feedIn":0,"gridCharge":98,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 08:48:21","ppv":434,"load":769,"cbat":11.6,"feedIn":0,"gridCharge":335,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 08:53:22","ppv":471,"load":460,"cbat":11.6,"feedIn":11,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 08:58:23","ppv":500,"load":2434,"cbat":11.6,"feedIn":0,"gridCharge":1934,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 09:03:24","ppv":562,"load":2458,"cbat":11.6,"feedIn":0,"gridCharge":1896,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 09:08:24","ppv":891,"load":2365,"cbat":11.6,"feedIn":0,"gridCharge":1474,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 09:13:25","ppv":1973,"load":328,"cbat":12,"feedIn":0,"gridCharge":21,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 09:18:26","ppv":1851,"load":650,"cbat":13.6,"feedIn":0,"gridCharge":60,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 09:24:09","ppv":1390,"load":358,"cbat":14.8,"feedIn":0,"gridCharge":79,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 09:29:09","ppv":1398,"load":1257,"cbat":16,"feedIn":0,"gridCharge":469,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 09:34:10","ppv":1340,"load":351,"cbat":16.8,"feedIn":0,"gridCharge":3,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 09:39:11","ppv":1449,"load":708,"cbat":17.6,"feedIn":808,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 09:44:12","ppv":1420,"load":490,"cbat":17.2,"feedIn":14,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 09:49:13","ppv":1448,"load":882,"cbat":17.6,"feedIn":18,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 09:54:14","ppv":1254,"load":498,"cbat":18,"feedIn":0,"gridCharge":16,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 09:59:14","ppv":1234,"load":506,"cbat":18.4,"feedIn":0,"gridCharge":56,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 10:04:15","ppv":892,"load":542,"cbat":18.4,"feedIn":0,"gridCharge":24,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 10:09:16","ppv":953,"load":528,"cbat":18.8,"feedIn":105,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 10:14:17","ppv":866,"load":538,"cbat":18.8,"feedIn":68,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 10:19:19","ppv":541,"load":814,"cbat":19.2,"feedIn":0,"gridCharge":53,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 10:24:19","ppv":506,"load":480,"cbat":19.2,"feedIn":26,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 10:29:20","ppv":474,"load":590,"cbat":19.2,"feedIn":3,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 10:34:21","ppv":1050,"load":619,"cbat":19.2,"feedIn":0,"gridCharge":66,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 10:39:23","ppv":1197,"load":555,"cbat":19.6,"feedIn":17,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 10:44:23","ppv":1258,"load":826,"cbat":20.4,"feedIn":0,"gridCharge":46,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 10:49:23","ppv":1251,"load":696,"cbat":20.8,"feedIn":0,"gridCharge":134,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 10:54:24","ppv":1261,"load":577,"cbat":21.6,"feedIn":12,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 10:59:24","ppv":1298,"load":512,"cbat":22,"feedIn":12,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 11:04:25","ppv":1355,"load":526,"cbat":22.8,"feedIn":0,"gridCharge":11,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 11:09:26","ppv":1313,"load":454,"cbat":24,"feedIn":32,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 11:14:26","ppv":1202,"load":756,"cbat":24.4,"feedIn":0,"gridCharge":65,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 11:19:27","ppv":1040,"load":496,"cbat":25.2,"feedIn":0,"gridCharge":55,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 11:24:28","ppv":1036,"load":580,"cbat":25.6,"feedIn":0,"gridCharge":34,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 11:27:47","ppv":1064,"load":545,"cbat":25.6,"feedIn":0,"gridCharge":17,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 11:29:09","ppv":1081,"load":547,"cbat":26,"feedIn":0,"gridCharge":6,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 11:31:53","ppv":1043,"load":549,"cbat":26,"feedIn":0,"gridCharge":16,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 11:36:53","ppv":1075,"load":542,"cbat":26.4,"feedIn":0,"gridCharge":44,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 11:41:54","ppv":1159,"load":803,"cbat":27.2,"feedIn":5,"gridCharge":0,"pchargingPile":0},{"sysSn":"AL400************68","uploadTime":"2024-10-16 11:46:55","ppv":1092,"load":493,"cbat":27.6,"feedIn":0,"gridCharge":31,"pchargingPile":0}],"daily":{"sysSn":"AL400************68","theDate":"2024-10-16","eCharge":1.3,"epv":3.3,"eOutput":0.04,"eInput":4.41,"eGridCharge":0.1,"eDischarge":1.6,"eChargingPile":0}}}}

**Comment by SMS-2018** [comment]
Adapter Alpha-Ess is green again, but no data is updated.

`<html><body>

alpha-ess.0 | 2024-10-16 12:03:26.522 | error | (COMPACT) Error code: 6026 - Internal Error (#2)
-- | -- | -- | --
alpha-ess.0 | 2024-10-16 12:03:26.521 | error | (COMPACT) Alpha ESS Api returns an error! Group: Settings_Discharge
alpha-ess.0 | 2024-10-16 12:03:26.455 | error | (COMPACT) Error code: 6026 - Internal Error (#1)
alpha-ess.0 | 2024-10-16 12:03:26.454 | error | (COMPACT) Alpha ESS Api returns an error! Group: Settings_Charge
alpha-ess.0 | 2024-10-16 11:59:22.038 | error | (COMPACT) Error code: 6026 - Internal Error (#1)
alpha-ess.0 | 2024-10-16 11:59:22.037 | error | (COMPACT) Alpha ESS Api returns an error! Group: Settings_Charge
alpha-ess.0 | 2024-10-16 11:58:21.198 | error | (COMPACT) Error code: 6026 - Internal Error (#1)
alpha-ess.0 | 2024-10-16 11:58:21.197 | error | (COMPACT) Alpha ESS Api returns an error! Group: Settings_Charge
alpha-ess.0 | 2024-10-16 11:57:20.600 | error | (COMPACT) Error code: 6026 - Internal Error (#1)
alpha-ess.0 | 2024-10-16 11:57:20.599 | error | (COMPACT) Alpha ESS Api returns an error! Group: Settings_Discharge
alpha-ess.0 | 2024-10-16 11:55:24.533 | info | (COMPACT) Wallbox data disabled! Adapter won't fetch Wallbox data. According states deleted.
alpha-ess.0 | 2024-10-16 11:55:24.288 | info | (COMPACT) Initialized states for : Summary
alpha-ess.0 | 2024-10-16 11:55:19.033 | info | (COMPACT) Initialized states for : Settings_Discharge
alpha-ess.0 | 2024-10-16 11:55:18.502 | info | (COMPACT) Initialized states for : Settings_Charge
alpha-ess.0 | 2024-10-16 11:55:17.946 | info | (COMPACT) Initialized states for : Energy
alpha-ess.0 | 2024-10-16 11:55:15.205 | info | (COMPACT) Initialized states for : Realtime
alpha-ess.0 | 2024-10-16 11:55:14.008 | info | (COMPACT) starting. Version 2.1.4 in /opt/iobroker/node_modules/iobroker.alpha-ess, node: v20.18.0, js-controller: 6.0.11
alpha-ess.0 | 2024-10-16 11:55:04.745 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
alpha-ess.0 | 2024-10-16 11:55:04.739 | info | terminating
alpha-ess.0 | 2024-10-16 11:55:04.234 | info | Got terminate signal TERMINATE_YOURSELF


</body>
</html>`

**Comment by Poshy163** [comment]
Yeah, using data from something like home assistant and that isnt the best for debugging. 

The issue boils down to the getLastPowerData call not actually showing any data, rather null

![image](https://github.com/user-attachments/assets/626b374c-50a6-46d0-9aea-175dad201d4b)
